### ISSUE TITLE
[BUG] mgconsole disconnects from the database after ~5 minutes of inactivity

### ISSUE THREAD

**Issue by vpavicic** [memgraph/memgraph#1114]
**Memgraph version**
Memgraph Platform with DB2.9.0 

**Environment**
Windows 10 with Docker

**Describe the bug**
After cca 5 minutes of inactivity I want to run a query and mgconsole returns the following error then reconnects 

![image](https://github.com/memgraph/memgraph/assets/95473291/2a5ab6e6-3091-42a7-84c1-c90981ae5e2e)

**To Reproduce**
1. Start Memgraph Platform with Docker
2. Run a query
3. Go and have your lunch
4. Run a query

**Expected behavior**
Memgraph is always connected with mgconsole

**Logs**
root@ff27aee38cc7:/tmp# cat memgraph-stderr---supervisor-iq9w2ziu.log
<frozen importlib._bootstrap>:228: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject

**Comment by katarinasupe** [comment]
Experience the same. In my case, more than one lunch was included, but yeah. I started Memgraph 2.9, ran a query successfully and left Memgraph running for a day or two. After that, I wanted to run a query, and since the mgconsole was left running, I ran the query from there and experienced the same issue. After that, it looked like I woke Memgraph up and ran a query without any issues.

<img width="520" alt="Screenshot 2023-07-27 at 12 32 38" src="https://github.com/memgraph/memgraph/assets/61758502/043ea307-e9bf-4ab2-bc3d-b50bd04557a6">

**Comment by andrejtonev** [comment]
> Experience the same. In my case, more than one lunch was included, but yeah. I started Memgraph 2.9, ran a query successfully and left Memgraph running for a day or two. After that, I wanted to run a query, and since the mgconsole was left running, I ran the query from there and experienced the same issue. After that, it looked like I woke Memgraph up and ran a query without any issues.
> <img alt="Screenshot 2023-07-27 at 12 32 38" width="520" src="https://user-images.githubusercontent.com/61758502/256546466-043ea307-e9bf-4ab2-bc3d-b50bd04557a6.png">

Did you also use Docker on Windows?

**Comment by katarinasupe** [comment]
Is this related to `--bolt-session-inactivity-timeout=1800`?

**Comment by andrejtonev** [comment]
@katarinasupe I believe so :)
We log the following when disconnecting because of the timeout `Shutting down session after {} seconds of inactivity`
It is logged at level `info`
If you catch this again, please check the logs.
You can also change at runtime the log level and if logging to stderr, if that is easier.

**Comment by katarinasupe** [comment]
Sure. I'll close this for now and reopen it if I notice it again. I haven't experienced such issues for a while now and based on similar reports I believe it was related to --bolt-session-inactivity-timeout flag.
