### ISSUE TITLE
Fix memory usage exceeds --memory-limit

### ISSUE THREAD

**Issue by steffiindrayani** [memgraph/memgraph#1222]
**Memgraph version**
Memgraph 2.8.0

**Environment**
- Using Docker
- OS: Ubuntu 22.04 64 bit
- 16vCPU(s) 32 GiB

**Describe the bug**
I have set up the --memory-limit in `etc/memgraph/memgraph.conf` to 17000 MiB and it has been reflected on the Memgraph Lab as shown below. However, whenever I run a query that exceeds the memory limit, the Memgraph does not stop the transaction automatically.
<img width="952" alt="Screenshot 2023-09-04 111644" src="https://github.com/memgraph/memgraph/assets/17632209/d3088140-d867-4022-bdf4-934899d95610">

Moreover, I have also tried to add `Query Memory Limit 10000 MB` at the end of my Cypher query. However, it still keeps exceeding the limit and does not stop automatically.

Would you mind guiding me how to correctly limit the Memgraph memory usage and any other configurations that I have missed? Really appreciate your help. Thanks in advance.

**To Reproduce**
1. Modify `memgraph.conf` file and set --memory-limit to 17000 MiB
2. Create 4M Nodes and 4M Relationships
3. Run a query with additional `Query Memory Limit 10000 MB` at the end

**Expected behavior**
Memgraph stops the query right after it reached the memory usage limit

**Comment by gitbuda** [comment]
Thanks for reporting! The team has already noticed this issue. Since there are multiple reported issues with the memory tracker (both issues and PRs have `memory` tags), we have already prioritized the work on that side. Hopefully, we can improve quickly.

PR to track is https://github.com/memgraph/memgraph/pull/1064, but the whole work will probably be split into multiple PRs.
CC @antoniofilipovic please write more details as soon as possible 😃

**Comment by antoniofilipovic** [comment]
@gitbuda This bug seems to be fixed with the new [PR](https://github.com/memgraph/memgraph/pull/1250). Tested with memory limit set on 2GiB and tried query which would overflow the limit, it stopped as soon as it reached the limit. 

For now, this will stay open for @steffiindrayani to test once this PR lands on the master.

**Comment by gitbuda** [comment]
#1250 got merged -> this issue should be resolved / experience massively improved.

**Comment by gitbuda** [comment]
TTL on this issue ~2 weeks (as soon as we release v2.12 it should be verified)

**Comment by as51340** [comment]
Closing because it is verified, works with 2.12.
