### ISSUE TITLE
Crash encountered about a query

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#1293]
I executed a query on my empty memgraph database and get an error.

memgraph version:2.11.0
operating system: windows 10
API：Cypher version 9
query:MATCH (n1) OPTIONAL MATCH p=(n1) RETURN 1;
error message:Query failed: Connection was closed by server

Actual behavior:
The query failed and the memgraph container exited abnormally with the error message.

**Comment by DavIvek** [comment]
We're currently working to resolve this bug, it seems that memgraph has a bug in a planner when using only a single node in the OPTIONAL MATCH clause.

**Comment by DavIvek** [comment]
Query: MATCH (n1) OPTIONAL MATCH p=(n1) RETURN 1;

The problem is in the way that memgraph makes logical plans for this type of query. Every time we define a path, for example p=(n1)-[]-(), memgraph will generate a ConstructNamedPath operator. Memgraph uses bound_symbols to save symbols for which it needs to generate a ScanAll operator. If the path has a relationship, memgraph will generate an Expand logical operator.

For the above query, the path is n1, since memgraph already created the ScanAll operator for n1, it won't do it again. Also, it won't generate an Expand operator because the path doesn't contain a relationship. A case like this isn't covered, so the query will fail and the memgraph will crash.

**Comment by ljhhuxiaoba** [comment]
Thank you for your explanation, please let me know when this issue is fixed!

**Comment by DavIvek** [comment]
PR #1318 should fix this bug with the OPTIONAL MATCH clause. 
@ljhhuxiaoba If you want me to help you with your use case you can reach me at david.ivekovic@memgraph.io. Also, feel free to [join](https://discord.com/invite/memgraph) the memgraphs discord channel.
