### ISSUE TITLE
Crash caused when using path in property value

### ISSUE THREAD

**Issue by ljhhuxiaoba** [memgraph/memgraph#1331]
I executed a query on my empty memgraph database and get a crash.

memgraph version:2.11.0
operating system: windows 11
API：Cypher version 9
query:CREATE p0=()-[:T0]->() MERGE ({k:(size(p0))}) RETURN 1
error message:Query failed: Connection was closed by server

Actual behavior:
The query failed and the memgraph container exited abnormally with the error message.

**Comment by karmenrabar** [comment]
Hello @ljhhuxiaoba, great news - Memgraph has a new release, 2.14., which includes the fix for this issue! Could you check if the newest version works as expected for you now? Check out our release update on Discord, here's the [link](https://discord.com/channels/842007348272169002/1047507324555767858/1200107892968271956). :)
