### ISSUE TITLE
Memgraph fails with double free assert 

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1377]
**Memgraph version**
Which version did you use?

**Environment**
Some information about the environment you are using Memgraph on: operating
system, how do you connect, with or without docker, which driver etc.

**Describe the bug**

**To Reproduce**
1. Run the following query '...'

**Expected behavior**

**Logs**
Logs are visible in this [comment](https://github.com/memgraph/memgraph/issues/1350#issuecomment-1766562020 )

**Additional context**

**Comment by antejavor** [comment]
This was open to handle [this comment](https://github.com/memgraph/memgraph/issues/1350#issuecomment-1766562020)

**Comment by gato** [comment]
Memgraph version:
2.11.0 (latest platform docker image)

Environment:
Docker's Memgraph platform image running on a Mac M1 host

Describe the bug:
running the same bunch of queries over an over again makes the server fail eventually. 

To Reproduce

Just running the same bunch of queries over an over again generate this issue. 
Hitting the server with just 1 or 2 processes doing this didn't seem to produce the error even running for longer periods of time. But using 4 or more processes will make the server throw the error in less than 15 seconds.

Note: Each process generates an identical graph but with different labels just to avoid collisions between them (generating disjoints graphs as a result although they live on the same database). Also each process generates their own indexes on labels and labels+attributes for performance reasons. 
just as a note each process updates a couple of nodes and edges and after that runs a query on top of the resulting graph, then again more updates and then a query and many times let's say we do about 6M updates on the graph, but the resulting graph is small about 450 nodes and 500 edges.
this shows the memory usage for 1, 2 and 4 processes (4 processes is after the server restarts what it recovers, as you see there are no indexes, but when running it creates 32 indexes)
<img width="1761" alt="1p" src="https://github.com/memgraph/memgraph/assets/638526/9a94a1a1-17f6-45dc-92ba-7bd829c17f00">
<img width="1753" alt="2p" src="https://github.com/memgraph/memgraph/assets/638526/f6a61986-1929-4e62-b91f-38d37922e943">
<img width="1759" alt="3p" src="https://github.com/memgraph/memgraph/assets/638526/2856248b-dabb-4bb1-9d00-db58e714ac06">


Expected behavior: 
processes will run until they finish or Memgraph runs out of memory.

Logs
Logs are visible in this https://github.com/memgraph/memgraph/issues/1350#issuecomment-1766562020

Additional context
Tested using Transactional and Analytical modes same results

**Comment by antejavor** [comment]
Hi @gato, we have the debug image for Memgraph 2.11 that I have shared on [the issue](https://github.com/memgraph/memgraph/issues/1350#issuecomment-1766080563) you commented initially. 

Can you spin up your workload using that image and send us a core dump? This massively helps us debug and see what the issue is. 

Also, sharing queries you are using in the process of creating data and hitting the database will be helpful for us.

**Comment by gato** [comment]
Hi @antejavor, 

Would you mind point me to the arm64 image? as i'm running everything on a Mac M1?

Thanks.

**Comment by as51340** [comment]
@gato about warnings you see when you start Memgraph: They aren't nice to see but they don't create any problems. The reason why warnings are generates is because of clearing python cache __pycache__ and reloading of imported packages. Python packages should deal with it successfully and great majority of them does so but there are few which don't like this operation like PyTorch, DGL, igraph...

**Comment by gato** [comment]
@as51340 no problems with the warnings, just mentioned them because they were in the logs and as i didn't know if they were related or not I pasted them for you to decide.

**Comment by antejavor** [comment]
Hi @gato, I encountered strange issues during the arm image build, so it takes some time. I will try to provide you with one ASAP, here on the issue.

**Comment by gato** [comment]
Hi @antejavor!
With latest platform version [2.12.0-memgraph2.12.0-lab2.9.0](https://hub.docker.com/layers/memgraph/memgraph-platform/2.12.0-memgraph2.12.0-lab2.9.0/images/sha256-4f9f0f21a1dc0e8c89fb20b8d75d60f07188c1771aec6077fb4db3741c9f2991?context=explore)
issue can't be reproduced. I'm currently able to run 100 process in parallel and they run smoothly. 
So, this bug can be closed from my POV. Thanks.

**Comment by as51340** [comment]
Awesome, glad to hear that!

**Comment by antejavor** [comment]
@gato Thanks for keeping us in the loop, and sorry for a bit of wait for ARM images. 

 We have an active community on Discord where we provide direct community support, if you are not on discord server consider joining: [discord invitation link](https://discord.gg/UpH4hSZa )

**Comment by gato** [comment]
@antejavor Thanks, I'm already there :)
