### ISSUE TITLE
many OPTIONAL MATCH make execution plans worse, scanAll operator and large Cartesian products occur

### ISSUE THREAD

**Issue by penghs520** [memgraph/memgraph#1470]
**Memgraph version**
v2.12.0

**Describe the bug**
As title

**To Reproduce**
Here's a working example in the  'hetionet' dataset:
```cypher
profile MATCH (gene:Gene)
WITH gene limit 1000
OPTIONAL MATCH (gene)<-[:UPREGULATES_DuG]-(d1:Disease)
WITH gene,collect(d1) as d1
OPTIONAL MATCH (gene)<-[:ASSOCIATES_DaG]-(d2:Disease)
WITH gene,d1,collect(d2) as d2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_DdG]-(d3:Disease)
WITH gene,d1,d2,collect(d3) as d3
OPTIONAL MATCH (gene)<-[:EXPRESSES_AeG]-(a1:Anatomy)
WITH gene,d1,d2,d3,collect(a1) as a1
OPTIONAL MATCH (gene)<-[:UPREGULATES_AuG]-(a2:Anatomy)
WITH gene,d1,d2,d3,a1,collect(a2) as a2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_AdG]-(a3:Anatomy)
WITH gene,d1,d2,d3,a1,a2,collect(a3) as a3
OPTIONAL MATCH (gene)<-[:BINDS_CbG]-(c1:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,collect(c1) as c1
OPTIONAL MATCH (gene)<-[:UPREGULATES_CuG]-(c2:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,c1,collect(c2) as c2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_CdG]-(c3:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,c1,c2,collect(c3) as c3
OPTIONAL MATCH (gene)-[:PARTICIPATES_GpBP]->(b1:BiologicalProcess)
WITH gene,d1,d2,d3,a1,a2,a3,c1,c2,c3,collect(b1) as b1
RETURN gene,d1,d2,d3,a1,a2,a3,c1,c2,c3,b1
```
![image](https://github.com/memgraph/memgraph/assets/52020193/018c7f53-481f-4984-80e7-1d5ab002ff94)
It will work well when i remove any one optional match:
```cypher
profile MATCH (gene:Gene)
WITH gene limit 1000
OPTIONAL MATCH (gene)<-[:UPREGULATES_DuG]-(d1:Disease)
WITH gene,collect(d1) as d1
OPTIONAL MATCH (gene)<-[:ASSOCIATES_DaG]-(d2:Disease)
WITH gene,d1,collect(d2) as d2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_DdG]-(d3:Disease)
WITH gene,d1,d2,collect(d3) as d3
OPTIONAL MATCH (gene)<-[:EXPRESSES_AeG]-(a1:Anatomy)
WITH gene,d1,d2,d3,collect(a1) as a1
OPTIONAL MATCH (gene)<-[:UPREGULATES_AuG]-(a2:Anatomy)
WITH gene,d1,d2,d3,a1,collect(a2) as a2
OPTIONAL MATCH (gene)<-[:DOWNREGULATES_AdG]-(a3:Anatomy)
WITH gene,d1,d2,d3,a1,a2,collect(a3) as a3
OPTIONAL MATCH (gene)<-[:BINDS_CbG]-(c1:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,collect(c1) as c1
OPTIONAL MATCH (gene)<-[:UPREGULATES_CuG]-(c2:Compound)
WITH gene,d1,d2,d3,a1,a2,a3,c1,collect(c2) as c2
//OPTIONAL MATCH (gene)<-[:DOWNREGULATES_CdG]-(c3:Compound)
//WITH gene,d1,d2,d3,a1,a2,a3,c1,c2,collect(c3) as c3
OPTIONAL MATCH (gene)-[:PARTICIPATES_GpBP]->(b1:BiologicalProcess)
WITH gene,d1,d2,d3,a1,a2,a3,c1,c2,collect(b1) as b1
RETURN gene,d1,d2,d3,a1,a2,a3,c1,c2,b1
```
![image](https://github.com/memgraph/memgraph/assets/52020193/acb95979-8cc8-4df3-a06a-8490dc93669a)

**Expected behavior**
Optimize execution plans for multiple optional matches

**Comment by karmenrabar** [comment]
Appreciate bringing this to our attention, we will look into it and get back to you

**Comment by DavIvek** [comment]
Hi @penghs520 !
When you execute a query, Memgraph has to create a plan for the given query. Memgraph will create multiple queries, and then based on the query cost estimator, it will pick the one it thinks is the best. 
Since the query you provided is a large one with multiple possibilities of execution, it will create a lot of potential queries. There is a configuration flag "--query-max-plans" with a default value of 1000. The reason you are not getting the best query plan is due to the desired plan not being in those 1000 ones. If you increase the value of a given flag, you'll get the desired plan. 
The planning phase might take longer, but the execution will be much faster. Also, after you generate a plan for the given query and execute it, that plan will get cached, so the next time you try to run the same query, the whole process will be much faster.

Can you check if this helps you or are you experiencing any other issues with the planner?

**Comment by DavIvek** [comment]
Closing since this doesn't look like an issue to me.
