### ISSUE TITLE
GraphQL end2end test hangs under CI

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#1511]

**Comment by DavIvek** [comment]
The issue is about a bug in our code. To be more precise, when we were callingCypherMainVisitor::visitCallProcedure in cypher_main_visitor.cpp, we wouldn't handle the case when the desired procedure wasn't found. That way we had reference to std::nullopt which we were accessing in a wrong way and that led us to SEGFAULT.
In this case, the connection between the server and client would continue to hang out, but there wouldn't be a valid response.
