### ISSUE TITLE
Can I access multiple datasets at the same time?

### ISSUE THREAD

**Issue by 1191000814** [memgraph/memgraph#1596]
If I use python api to access the memgraph, can I access multiple datasets at the same time? because I want to perform calculations using data from multiple datasets.

**Comment by 1191000814** [comment]
Like the 'join' clause in mysql?

**Comment by karmenrabar** [comment]
Hello @1191000814 :) Thank you for posting these questions. In order to understand your situation better, could you let me know if perhaps you're running multiple instances on one machine ? There is a multi-tenancy support in Memgraph which enables users to manage multiple isolated databases within a single instance. 

Could you let me know want kind of data you want to retrieve with the join clause ? Graph databases use a graph-based approach where relationships are explicit and traversed directly, unlike JOIN operations in relational dbs - I assume you already know but we can discuss this. 

We can continue the conversation on Discord, it'll be more efficient and easier ! Feel free to [join](https://discord.com/invite/memgraph) if you haven't already.

**Comment by katarinasupe** [comment]
Hi @1191000814, closing this issue because of the inactivity. Since this issue is more of a support nature, please [join](https://discord.com/invite/memgraph) Discord and ask for further help.
