### ISSUE TITLE
Split function causes OutOfMemory bug 

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#1625]
**Memgraph version**
Memgraph v2.13

**Environment**
Docker 

**Describe the bug**
Running a split function on a string with an empty argument should probably separate the string into characters. 
In current implementations, it eats all the memory. 

**To Reproduce**
RETURN split('abc','') as outOfMemoryBug

**Expected behavior**
List of a,b,c strings.  

**Logs**

Memory limit exceeded! Attempting to allocate a chunk of 5.00GiB which would put the current use to 7.55GiB, while the maximum allowed size for allocation is set to 7.34GiB.

**Comment by katarinasupe** [comment]
@antejavor is this duplicated? https://github.com/memgraph/memgraph/issues/609

**Comment by andrejtonev** [comment]
> @antejavor is this duplicated? https://github.com/memgraph/memgraph/issues/609

@katarinasupe, yes :smile:

**Comment by andrejtonev** [comment]
This is easily fixed by changing the split logic. It doesn't support empty delimiter and just runs forever.
I fixed the issue, but I'm not 100% sure I like allowing `split("abc", "")` with an empty delimiter. 
I would rather have two functions; one `split("abd", "not empty") ` and another one `split("abc")` that just splits every character.

**Comment by andrejtonev** [comment]
closes https://github.com/memgraph/memgraph/issues/609
