### ISSUE TITLE
Memory consumption extremely high on in-memory transactional mode after import without freeing

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#1685]
**Memgraph version**
v2.14

**Environment**
Docker

**Describe the bug**
After ingesting 3 million nodes with one property, memory does not seem to free and memory usage shows 3GB consumed. It is never freed. If you restart the same container for the data to be restored from the snapshot, the memory usage shows around 700MB which is the estimated amount. Something seems not to free in the deltas or memory is not given back to the process, that's an assumption

**To Reproduce**
1. Start Memgraph
2. Run `FOREACH (i in range(1, 3000000) | CREATE (:Label1:Label2:Label3:Label4:Label5:Label6));`
3. Observe memory usage
4. Restart Memgraph
5. Observe memory usage
6. Stop Memgraph
7. Start Memgraph with fresh database
8. run `STORAGE MODE IN_MEMORY_ANALYTICAL;`
9. run `FOREACH (i in range(1, 3000000) | CREATE (:Label1:Label2:Label3:Label4:Label5:Label6));`
10. Observe much less memory being used in the analytical mode than the transactional mode

**Expected behavior**
Memory should be freed so users don't run into Out Of Memory Exceptions.

**Additional context**

**Verification Environment**
Once we fix it, what do you need to verify the fix?
Do you need:
* Plain memgraph package -> for which Linux?
* Plain memgraph Docker image?
* Which architecture do you use ARM | x86?
* Full Memgraph platform?

### NOTE: A bunch of work here has been done, but still TODOs:
- [x] Ensure deltas are allocated to separate pages than those of storage

**Comment by Ignition** [comment]
5. Using a common allocation arena results in interleaved allocations.

This means vertices and delta allocation happen in that order and use a common page.

`| V D V D V D | V D V D . . |`

When Deltas are freed their space in the page can be reused.

`| V . V . V . | V . V . . . |`

But the number of pages does not go down because the vertices can't relocate. Hence the resident memory does not go down after the transaction has finished.

TODO: use separate allocation arenas, which will force the two sub systems to use different page sets.

`| V V V V V . |` + `| D D D D D . |`
will become 
`| V V V V V . |` + ` `

**Comment by Ignition** [comment]
More delta reduction 80B -> 56B #1747

**Comment by Ignition** [comment]
Status update, with all the changes done so far the effect is less severe. I have just retested:
```
IN_MEMORY_TRANSACTIONAL ~750MiB
IN_MEMORY_ANALYTICAL    ~550MiB
```
ATM there is still the shorter lived deltas being allocations being interleaved with longer lived storage allocations.

**Comment by Ignition** [comment]
@gitbuda should we mark this issue as done, all identified issues are resolved.

**Comment by gitbuda** [comment]
@Ignition, yep, you right, closing this issue because a lot has been done to improve on this side -> let's create new issues if needed.
