### ISSUE TITLE
Snapshots are being created periodically in in-memory analytical storage mode

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#1824]
**Memgraph version**
2.15

**Environment**
Docker, Mac M1

**Describe the bug**
Snapshots are being created periodically in in-memory analytical storage mode. This was not the intended behavior when the feature was implemented.

**To Reproduce**
Start Memgraph in in-memory analytics mode. Snapshot will be created after `--storage-snapshot-interval-sec`. 

**Expected behavior**
Snapshots are not being created.

**Additional context**
Workaround: set `--storage-snapshot-interval-sec` to 0. 
[Internal discussion.
](https://memgraph.slack.com/archives/CEVJCLKKL/p1710496928937779)

**Comment by antoniofilipovic** [comment]
The main problem is that the user needs to disable periodic snapshots and also disable writing on WAL files for periodic snapshots to be disabled in in-memory-analytical mode. From the user's perspective, that should be disabled by default. If the user enables periodic snapshots we should still have them disabled in in-memory-analytical storage mode by default (override user) as creating snapshots blocks the whole Memgraph, because a write transaction that is executed at the same time as the snapshot is created can lead to the creation of an invalid snapshot.

**Comment by katarinasupe** [comment]
Feedback from the user: 

> I think having a flag to specify periodic snapshots in analytical mode would be a great option to keep around still. It could default to 0 in analytical mode, but if I were to specify --storage-snapshot-interval-sec to 300 on startup, it would be great to keep that behavior. Otherwise I'd have to write an external chron job to periodically send the query CREATE SNAPSHOT to memgraph.
