### ISSUE TITLE
Query modules in C++ are being congested by the unique lock

### ISSUE THREAD

**Issue by Josipmrden** [memgraph/memgraph#1942]
**Memgraph version**
v2.16.0

**Environment**
Ubuntu 22.04

**Describe the bug**
It seems that the memory dispatch guard is taking around 30% time on holding the unique lock while registering and unregistering the thread. Furthermore, the Register and Unregister methods are both called as many times as the query module is run (so at least once per query, but can be more)

Query module for testing

```
#include <mgp.hpp>
#include <string>

void isEqual(mgp_list *args, mgp_func_context *ctx, mgp_func_result *res, mgp_memory *memory) {
    mgp::MemoryDispatcherGuard guard(memory);

    const auto arguments = mgp::List(args);
    auto result = mgp::Result(res);

    std::string output = std::string(arguments[0].ValueString());
    std::string input = std::string(arguments[1].ValueString());

    result.SetValue(output == input);
}
 
extern "C" int mgp_init_module(struct mgp_module *module, struct mgp_memory *memory) {
  try {
    mgp::MemoryDispatcherGuard guard(memory);
 
    mgp::AddFunction(isEqual, "is_equal",
                     {mgp::Parameter("output", mgp::Type::String), mgp::Parameter("input", mgp::Type::String)}, module, memory);
  } catch (const std::exception &e) {
    return 1;
  }
  return 0;
}
 
extern "C" int mgp_shutdown_module() {
  return 0;
}
```

**To Reproduce**
1. `foreach (i in range(1, 10000000) | CREATE (:Node {id1: toString(i), id2: toString(i)}));`
2. Observe how much time it takes to execute `match (n) where equality.is_equal(n.id1, n.id2) = true return count(*);`
3. observe how much time it takes to execute the command above in parallel (use 2 consoles and run one immediately after the other) -> the time is more than doubled for both queries

**Expected behavior**
Queries shouldn't be that slow

Flamegraph
![Screenshot from 2024-04-15 16-12-20](https://github.com/memgraph/memgraph/assets/22621791/992cbf8c-7851-4ffa-b6c2-336c1d0c6d3e)

**Comment by DavIvek** [comment]
The introduction of the [MemoryDispatcherGuard](https://github.com/memgraph/memgraph/pull/1158) serves the purpose of tracking which thread utilizes a pointer to manage memory resources. Since mgp::memory is a global object, all procedures and functions within a single shared library will reference the same mgp::memory object. Consequently, concurrent invocation of such callables from multiple threads can result in improper memory utilization. This issue extends to scenarios where the same callable is invoked from different user sessions. 
The constructor of MemoryDispatcherGuard invokes the` MemoryDispatcher::Register` function, which attempts to acquire a unique lock. However, this approach poses a significant bottleneck when the module is invoked multiple times within a single query. Acquiring a unique lock each time can lead to performance degradation.
