### ISSUE TITLE
Node property index incorrect update

### ISSUE THREAD

**Issue by tonijurjevic96** [memgraph/memgraph#2292]
Memgraph 2.19 

Node property index is not updating correctly in the following use-case when additional node have same property name as already created node suggesting that it is not taking into account label for node when updating index.

Use case:

```
CREATE INDEX ON :A;
CREATE INDEX ON :A(pid);
CREATE INDEX ON :B;
CREATE INDEX ON :B(did);

UNWIND range(1, 1000000) AS id
CREATE (:A {pid: id});

UNWIND range(1, 1000000) AS id
CREATE (:B {did: id});

```

`SHOW INDEX INFO;`
![Screenshot from 2024-08-27 11-19-39](https://github.com/user-attachments/assets/8f241b12-654b-4494-acc8-6af43ab91e53)

```
UNWIND range(1, 1000000) AS id
MATCH (n:A {pid: id}), (m:B {did: id})
CREATE (l:C {pid: n.pid, did: m.did});
```

`SHOW INDEX INFO;`
![Screenshot from 2024-08-27 11-21-02](https://github.com/user-attachments/assets/3739329f-382b-409f-b6f7-a820afd3f02e)

**Comment by gitbuda** [comment]
NOTE: The reported index count might not be 100% accurate because that is just the number of entities in the skiplist (the actual number of entities can be lower because of concurrency implementation), but that seems to not be the case here.

It seems (on CREATE) that the wrong index gets update (new entries are added) somehow 🤔
