### ISSUE TITLE
Memgraph debug enviroment

### ISSUE THREAD

**Issue by divya1997** [memgraph/memgraph#2299]
I am planning to use memgraph for my circuit traversal and simulation tool. My primary requirement is the core graph DB, I don't necessarily require the memgraph platform and other products.

Right now I am able to compile memgraph on Ubuntu 22.04 using dockerfile. But I am still thinking on best way to setup debug environment for memgraph. 
Let me know if you guys have some documents to setup debug environment in windows using dockerfile. 
Have a good day!

**Comment by matea16** [comment]
Hi @divya1997, although we don't have a lot of the documents to set up a debug environment in Windows, here are some materials that might be helpful to you:
https://memgraph.com/docs/getting-started/build-memgraph-from-source
https://memgraph.notion.site/Memgraph-Internals-12b69132d67a417898972927d6870bd2

I'll close this since it's not an issue, but feel free to [join us on Discord](https://discord.gg/memgraph) if you have any further questions. We have a pretty active community there and you'll get your answers in no time :)

**Comment by divya1997** [comment]
Thanks @matea16
