### ISSUE TITLE
Instance crashes while exiting

### ISSUE THREAD

**Issue by andrejtonev** [memgraph/memgraph#2382]
**Memgraph version**
Which version did you use?
v2.20

**Describe the bug**
The instance would sometimes crash while closing.
This would happen only if a stream and/or ttl was running.

**To Reproduce**
1. Start ttl
2. Ctrl+C
3. Segfault while preparing ttl query

**Expected behavior**
Clean shutdown

**Comment by katarinasupe** [comment]
@andrejtonev can this cause snapshot not being created on exit? (when having -snapshot-on-exit set to true) I am just thinking about smth else so want to know if that's true.

**Comment by andrejtonev** [comment]
@katarinasupe yes, we would miss the snapshot on exit.
we create the snapshot when destroying the storage itself. this segfault happens before that. 
but keep in mind that this bugfix only fixes crashes that happen because of enabled streams or ttl.

**Comment by katarinasupe** [comment]
Thank you! I get that this fixes only crashes in some cases, but I wanted to understand if data recovery in case of a database crash would have to be done with WALs instead of snapshots (snapshot is not done on exit -> WALs are latest). This kind of recovery is much slower on a large scale, and that's why I am interested in learning the effects of database crashes on the recovery process.
