### ISSUE TITLE
The FOREACH language construct for performing an operation on every list element

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/memgraph#308]
While working on different query examples I was frequently missing the FOREACH construct. Also, noticed that our developer users feel that would be a nice addition.

**Comment by katarinasupe** [comment]
I'll come up with a few useful examples and let you know :)

**Comment by katarinasupe** [comment]
Possible usage of `FOREACH` clause:

1. Executing update commands on elements in a path. Example:
```
MATCH path=(n)-[*]->(m)
WHERE n.name = 'start' AND m.name = 'finish'
FOREACH (i IN nodes(path) | SET i.checkpoint = true);
```
2. Executing update commands on a list created by aggregation 
```
MATCH (n:Person)
WITH collect(n.age) AS ages
FOREACH (age IN ages | CREATE (m:Age {amount: age}));
```

The `UNWIND` clause is better when you want to execute an additional `MATCH` for each element in a list, and within `FOREACH` you can use clauses `SET`, `REMOVE`, `CREATE`, `MERGE`, `DELETE`, and `FOREACH`.
Also, I was creating `json_util.load()` query module for loading `JSON` and thought it would be useful to be able to iterate with `FOREACH`.

**Comment by gitbuda** [comment]
@katarinasupe, these are very valid points 😄

In addition to what you've written, `FOREACH` is a very convenient "imperative" clause used to manipulate data in general. E.g., `FOREACH` can help mocking data without writing an application or query modules code.

`FOREACH` seems more straightforward for the less technical user. Even for more technical users, a query containing the  `FOREACH` clause might be faster to implement.

**Comment by FloweryScythe13** [comment]
Adding to this with a user's perspective (per Katarina's suggestion): 

I've found so far that in multiple scenarios where one is performing write operations and there is a one-to-many relationship built into one's primary data model, one needs to rely on computationally less efficient workarounds due to the lack of current support for the FOREACH clause. A key example here is of course Twitter. There are several different popular tools that source data from Twitter (whether it's Twint, the official firehose API, or dataset CSVs directly released by the Twitter Trust & Safety department in the case of state-sponsored information operations that their internal staff have found), and although those tools have some differences in their data schema, they all generally output data in the form of tabular rows of tweets. Across all the tools I've seen, the tweet schema always contains columns that define a one-to-many relationship for the given property of a Tweet, such as `hashtags`, `urls`, and `user_mentions` (or their equivalents). For example, below is a tweet from a troll account that was operated by the Russian Internet Research Agency and which was released by Twitter in their Northern Africa IO dataset:

`tweetid,userid,user_display_name,user_screen_name,user_reported_location,user_profile_description,user_profile_url,follower_count,following_count,account_creation_date,account_language,tweet_language,tweet_text,tweet_time,tweet_client_name,in_reply_to_userid,in_reply_to_tweetid,quoted_tweet_tweetid,is_retweet,retweet_userid,retweet_tweetid,latitude,longitude,quote_count,reply_count,like_count,retweet_count,hashtags,urls,user_mentions`
`3.76047909948883E+017,FDAiQiDNukYhjuXtuoj8oXCk9DaeuDk6dWKCID+Kscc=,FDAiQiDNukYhjuXtuoj8oXCk9DaeuDk6dWKCID+Kscc=,FDAiQiDNukYhjuXtuoj8oXCk9DaeuDk6dWKCID+Kscc=,,,,51,398,2013-07-01,en,en,RT @UNPeacekeeping: AU-#UN Mission in #Darfur recovers body of one of four missing peacekeepers swept away by floods http://t.co/OdB4aNllE6…,2013-09-06 18:23,Mobile Web (M2),,,,True,,376029614071874,absent,absent,0,0,0,0,"['UN', 'Darfur']",['http://ow.ly/oDnGq'],"['46003622']"
`

To load a CSV file of bulk Twitter data with the above schema into Neo4J, one might use the following Cypher queries (credit to Adam Crowley and his repo at https://github.com/adam-cowley/twittergraph): 
`// Create Tweet
MERGE (t:Tweet {id_str:status.id_str})
SET t.text=status.text,t.created_at=status.created_at,t.retweet_count=status.retweet_count, t.favorite_count=status.favorite_count

// Create Author
MERGE (u:User {screen_name:user.screen_name})
SET u.name = user.name, u.friends_count = user.friends_count, u.followers_count = user.followers_count, u.picture=user.profile_image_url

MERGE (u)-[:TWEETED]->(t)

// Create Hashtags
FOREACH (h in entities.hashtags | MERGE (ht:Hashtag {name:h.text}) MERGE (t)-[:MENTIONS_HASHTAG]->(ht))

// Mentions
FOREACH (m in entities.user_mentions | MERGE (mu:User {screen_name:m.screen_name})  MERGE (t)-[:MENTIONS_USER]->(mu))

// URLs
FOREACH (m in entities.urls | MERGE (mu:URL {url:m.url})  MERGE (t)-[:MENTIONS_URL]->(mu))
.....
`
and so on. 

To accomplish the same task in Memgraph, I am able to use the same logic for creating the core Tweet, the user who authored the tweet, and other nodes that have a 1:1 relationship with the Tweet. However, as we have discussed on Discord in the past, I must use triggers to create nodes from the list properties of each Tweet due to the lack of FOREACH support - one trigger for each list property. This is a more involved and laborious workaround than it looks at first glance, because when each trigger executes in the database, the JSON record object for the given tweet (the one that was received from Kafka and used to generate the original Cypher write statement above) is no longer in scope and cannot be accessed. As a consequence of this, I must write the list of values for the given property onto the Tweet node during initial creation, so that the values list is present on each element in the returned `createdVertices` collection and thus is passed correctly to the given trigger:
`result_queries.append(
                mgp.Record(
                    query=(f'''MERGE (t:Tweet{
                            ":Retweet" if tweet_dict["is_retweet"] else ""
                        } {{id: $tweet_id}}) 
                        SET t.created_at=localdatetime($created_at), 
                        t.text=$text, t.replies_count=$replies_count, 
                        t.retweets_count=$retweets_count, t.quote_count=$quote_count, t.like_count=$like_count,
                        t.language=$tweet_language, **_t._hashtags=$hashtags_**,
                        **_t._mentions=$user_mentions_**{", **_t._urls=$tweet_urls_**" if tweet_dict["is_retweet"] is False and tweet_dict["urls"] else ""}
                        

                        '''),
`
These list properties aren't really supposed to be part of the graph data model for a Tweet, though - they're supposed to be their own node category. That's why I have prefixed each property with _ above, to denote them as something like a private property in a class. 

After each created Tweet is committed to the database, the three triggers then call the corresponding custom write procedures, which is an extra computational step that isn't always needed (like if the tweet has no hashtags or URLs and mentioned no users): 
`        memgraph.execute(
            '''CREATE TRIGGER created_tweet_trigger_mentions
            ON () CREATE AFTER COMMIT EXECUTE
            CALL twitter_procs.create_mentions(createdVertices)'''
        )
`

Then we get to the custom write_procedure implementations themselves. It is true that iterating over things within such modules is easy enough, but you also have to query and iterate over the whole existing graph for the set of "child" nodes that you want to MERGE into. One can do that first in a Cypher clause within the trigger definition, or in Python etc within the code of the custom write procedure, but you still have to do it as yet another step. 

Here is example code from one of my workaround custom write-procedures: 
`
@mgp.write_proc
def create_mentions(context: mgp.ProcCtx,
                    created_vertices: mgp.Any) -> mgp.Record():
    for vert in created_vertices:
        if vert.labels[0] == "Tweet" and "_mentions" in vert.properties.keys():
            user_mentions = vert.properties["_mentions"]    
            
            assert isinstance(user_mentions, tuple)
            if len(user_mentions) > 0:
                user_vertices_list = [vertex for vertex in context.graph.vertices if any(label == "User" for label in vertex.labels)]

                for i in range(0, len(user_mentions)):
                    # Note to self: name of the below is walrus operator or assignment expression
                    #target_user = _[0] if (_:= [x for x in user_vertices_list if x.properties["id"] == user_mentions[i]]) else None
                    _ = [x for x in user_vertices_list if x.properties["id"] == user_mentions[i]]
                    target_user = _[0] if len(_) > 0 else None
                    if target_user is not None:
                        edge = context.graph.create_edge(vert, target_user, mgp.EdgeType("MENTIONS"))
                    else:
                        target_user_vertex = context.graph.create_vertex()
                        target_user_vertex.add_label("User")
                        log_to_stderr_by_force(f"ID of new User vertex is: {target_user_vertex.id}")
                        target_user_vertex.properties["id"] = user_mentions[i]
                        edge = context.graph.create_edge(vert, target_user_vertex, mgp.EdgeType("MENTIONS"))
                        
    return mgp.Record()
`

The above must be repeated for each list property. And it gets called after every vertex creation event, whether or not the vertex is actually a Tweet. 

It's rather a lot of code to have to write (and debug the first time around) when it could easily be accomplished by a one-line Cypher statement like `FOREACH (m in entities.user_mentions | MERGE (mu:User {screen_name:m.screen_name})  MERGE (t)-[:MENTIONS_USER]->(mu))` if such syntax was supported. 


P.S. Oh, by the way, while we're looking at that code - Memgraph's Python version doesn't seem to recognize the walrus operator that was introduced in Python 3.7 or 3.8, whichever version it was. That's the reason for the commented-out line of code.

**Comment by FloweryScythe13** [comment]
There is one other usage of the FOREACH clause that would be valuable for developers if Memgraph supported the clause: the ability to write _conditional_ logic to execute some write-only statement according to a given condition. You may say, "but we have the CASE statement for conditional evaluation already!". That is true, BUT... the CASE statement only lets you output a value based on your condition. It does not give the developer a way to conditionally _execute a statement_!

See the Neo4J documentation paragraph at https://neo4j.com/developer/kb/conditional-cypher-execution/#_using_foreach_for_write_only_cypher. If we had support for FOREACH in Memgraph, I would be able to tweak my above trigger definitions so that they only called their corresponding write_proc method for created Tweets, and not for created Users, Hashtags, URLs, and so on. So I could do: 
```CREATE TRIGGER created_tweet_trigger_mentions ON () CREATE AFTER COMMIT EXECUTE 
UNWIND createdVertices as vertex
 FOREACH (i in CASE WHEN vertex.labels CONTAINS("Tweet") THEN [1] ELSE [] END |
  CALL twitter_procs.create_mentions(vertex)
)...
```

That would allow me to, for example, run a trigger that processes shortened URLs into their full-length URL values only for Tweets that aren't retweets (because every retweet on Twitter includes a Twitter-shortened link to the tweet being retweeted, and those extra URLs being in your graph wouldn't tell you anything interesting about the fake news websites and information that troll accounts are trying to spread on social media... they'd just act as noise to make identification & analysis of true disinformation operations within the dataset more difficult).

**Comment by Jim-Salmons** [comment]
I agree that supporting the `FOREACH` semantic would be _very_ helpful. As an expat Neo4j'er, I have been looking for an alternative graph database to rewrite (to keep accessible) my old **GraphGists** related to my #DigitalHumanities research. In them, I made use of `FOREACH` regularly.

I believe Memgraph will be well-served for the effort to support this construct for two interrelated reasons:

* Lack of `FOREACH` will be an early showstopper for expat Neo4j'ers looking for strong OpenCypher support as they make a transition to a new product and developer community. While workarounds are helpful for the highly motivated, having to rewrite legacy queries to make the leap to your product is a gating factor that will cost you new users and diminish their enthusiasm on making that critical platform choice decision.
* I believe the Memgraph Playground has the potential to be a Neo4j GraphGist replacement on steroids. Neo4j has not maintained the GraphGist platform/portal for years even though it was an innovation that stimulated great growth of their early passion-driven developer community. Memgraph Playground looks to be even better! Having `FOREACH` in the semantics of Playground presentations/lessons etc. will open up a LOT of potential expressiveness without needing to turn to non-OpenCypher means to do data-setup, -loading, and -transformations, etc.. Currently, the Playground neatly stays within the Memgraph ecosystem without needing to incorporate other language adapters to do data prep/massaging the way you might do to use Memgraph in a Jupyter Notebook, for example.

**Comment by antaljanosbenjamin** [comment]
@Jim-Salmons I agree with you on that `FOREACH` is a good addition to Memgraph, I would like to point that out it is not part of [openCypher](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf), but Neo4j's [Cypher](https://neo4j.com/docs/cypher-manual/current/clauses/foreach/) language. The difference between them is tiny, but existing.

**Comment by Jim-Salmons** [comment]
I was an early member of the Neo4j community before it evolved into a more “enterprise” culture, so my actual Cypher “chops” are rusty at best. After prototyping ideas related to my Digital Humanities research agenda in GraphGists, I have been more focused on evolving the schema for the MAGAZINEgts ground truth storage format and its reference implementation on the digital collection of Softalk magazine at the Internet Archive. This is an XML format supporting an integrated complex document structure and content depiction model based on a metamodel subgraph design pattern. 

ITMT, Neo4j has apparently abandoned the GraphGist technology and public portal which has left my still-useful GraphGists dysfunctional.

Now that I am getting to the point that I want to do some tool prototyping related to my research, I am looking for a graph database where I can reinvigorate my Cypher-based work. It would seem that the delta between Neo4j’s and OpenCypher’s FOREACH would be relatively easy to overcome as far as reusing legacy queries at the scale of my personal research use. It might be a time-effort concern on a large-scale production application however.

Regardless of these differences—which I will obviously need to more fully understand if/when Memgraph supports it—I think my intuitive sense is a reasonable point that a FOREACH semantic would be a good thing for expanding the expressive power of the amazing Playground environment.

**Comment by antaljanosbenjamin** [comment]
> Regardless of this and other differences between the open and Neo4j implementations—which I will obviously need to more fully understand—I think my intuitive sense is a reasonable point that a FOREACH semantic would be a good thing for expanding the expressive power of the amazing Playground environment.

Definitely, that's why we are working [on it](https://github.com/memgraph/memgraph/pull/351)!
