### ISSUE TITLE
[BUG] Fix recovery on REPLICA

### ISSUE THREAD

**Issue by vpavicic** [memgraph/memgraph#373]
**Memgraph version**
Memgraph 2.2.1

**Environment**
Windows 10, Memgraph Lab, with Docker using memgraph-platform image

**Describe the bug**
While testing replication I created multiple instances:

1: docker run -it -p 7687:7687 -p 3000:3000 -v mg_lib:/var/lib/memgraph memgraph/memgraph-platform
2: docker run -it -p 7688:7687 -p 3001:3000 -v mg_lib2:/var/lib/memgraph memgraph/memgraph-platform
3: docker run -it -p 7689:7687 -p 3002:3000 -v mg_lib3:/var/lib/memgraph memgraph/memgraph-platform

I demoted 2 and 3 to replicas and registered them from the main in SYNC mode...

Issue 1: I shut down instance 3, brought it back up with the same IP address... its role is main again... it doesn't remember it was a replica
The docs say "Each Memgraph instance will remember what the configuration was set to and will automatically resume with its role when restarted."

Issue 2: Docs say that replication in SYNC mode will fail if all REPLICA instances cannot confirm that they received the data and synced to the same state as the MAIN instance...  After shutting down and restarting instance 3 it is no longer a replica because of issue 1, then I shut down instance 2, created and deleted nodes and relationships on the MAIN.... no issues occurred and the MAIN committed the changes although the replica 2 couldn't confirm... 

**Expected behavior**
1. Restarted replica instance should remember it was a REPLICA instance and its configuration in regards to the replication process ONLY THIS HAS TO BE ADDRESSED
2. In SYNC mode the MAIN shouldn't commit changes if one/all of its replicas are down

**Comment by gitbuda** [comment]
1. When we implemented replication config recovery inside #415, seems like we only did that from the perspective of `MAIN` -> take a look at test cases inside [tests/e2e/replication/show_while_creating_invalid_state.py](https://github.com/memgraph/memgraph/blob/master/tests/e2e/replication/show_while_creating_invalid_state.py) -> I think we should reiterate and add the part in case `REPLICA` goes down. In other words, I think that part is a legit enhancement.
2. We actually discussed that if a replica is down, even if the mode is `SYNC`, we should return back to the user success, in the background, because data has been written to the serial log, and everything will be eventually replicated -> that part is something we should document in a better way.

**Comment by vpavicic** [comment]
2. Should we maybe return some kind of warning in the logs or not? i guess people monitor servers independently and would already know the replica instance is down?

**Comment by gitbuda** [comment]
> 2. Should we maybe return some kind of warning in the logs or not? i guess people monitor servers independently and would already know the replica instance is down?

Yes, we discussed that we'd add some form of notification, but we have to ensure that the notification is properly propagated to whatever client user is using 😄

**Comment by gitbuda** [comment]
For more details about `SYNC` aborts -> #381

**Comment by gitbuda** [comment]
Related https://discourse.memgraph.com/t/memgraphdb-replication/364

**Comment by katarinasupe** [comment]
Might be related to: https://discord.com/channels/842007348272169002/890968055339958292/1106152250662977556

**Comment by gitbuda** [comment]
NOTE: I moved this to v2.9 because we haven't been able to finish this because of other priorities. Once we do v2.8 release, we'll try to prioritize this as best as possible.
