### ISSUE TITLE
[BUG] Memgraph Lab: Undo Query `CMD` `Z` not working

### ISSUE THREAD

**Issue by D1no** [memgraph/memgraph#413]
**Memgraph version**
Latest

**Environment**
Mac M1 / All

**Describe the bug**
Every time I run a query, I can not undo. I am a newbie to Cypher and MemGraph so I make a lot of mistakes... want to try things out. That is incredible tedious, because I can not simply hit <kbd>CMD</kbd> + <kbd>Z</kbd> to go back. _Which is very very frustrating._

https://user-images.githubusercontent.com/2397125/174497106-b301a7bc-1ab1-4279-8377-f170a41c9629.mp4

**To Reproduce**
1. Open Memgraph Lab
2. Write Query
3. Run
4. Change Query to a mistake
5. Run
6. Hit <kbd>CMD</kbd> + <kbd>Z</kbd>
7. Can't revert the change.

**Expected behavior**

- I'd expect that anything I type can be reverted like any other text field

**Additional context**
I am a react guy, so I don't know angular. It seems angular is unmounting and re-rendering the text field component on `Run Query`. Not doing that should allow the users operations system to track `undo` functionality without any extra coding like any text field.

A stretch goal on top in regards of user experience would be,

- that if I hit <kbd>CMD</kbd> + <kbd>S</kbd> the query is saved in the log as saved
- that on the top right, above the query text window is an easy forward, backward and list menu that allows to step through the query log without context switching into the "latest queries" section.

**Comment by tonilastre** [comment]
@D1no, thanks for the great explanation of the issue!

You got it correct. `CMD` + `Z` currently only works within a context between two query runs. Your suggestions totally make sense. We will definitely add the following fixes:

* `CMD / CTRL` + `Z` to work regardless of the query run context
* `CMD / CTRL` + `S` to open up saving a query to query collection - btw once the query run completes, it is automatically added to the log (latest queries). Query collections are custom-saved queries.

> that on the top right, above the query text window is an easy forward, backward and list menu that allows to step through the query log without context switching into the "latest queries" section.

The above additional request is excellent too, we will think about how to integrate it 👍 

**Workaround**
In the meantime, you can set up a Lab layout to help you out with your workflow:

1. Click `Toggle horizontal split`, then click `Latest queries` to load it up in the bottom layout
2. In the top layout, click `Query execution` to load that up to the top layout
3. Now you don't need to change context because you have both information visible (check the image below)

![Screenshot 2022-06-24 at 10 07 56](https://user-images.githubusercontent.com/2602830/175493723-9ab6eb1a-fead-4bec-89ba-1a98aafce0ef.png)

**Comment by Josipmrden** [comment]
@tonilastre  is this fixed, can we close the issue?

**Comment by tonilastre** [comment]
> @tonilastre is this fixed, can we close the issue?

No, it isn't. `CMD` + `Z` works within a single query context meaning once you close Query Execution and open it again, the query history in the editor is refreshed. A user reported having `CMD` + `Z` working across the full query history.

**Comment by D1no** [comment]
Happened to not use memgraph, but are you guys fixing that? Change the text field to type text for browser based redo shouldn't be a big task -- but otherwise I'll close this?

**Comment by tonilastre** [comment]
Hey @D1no - have you switched to some other graph database vendor? 

Btw regarding your bug report, it has been fixed and released, so we can close this issue. Now, within that particular query execution context, `CTRL/CMD + Z` works even if you run a successful or failed query. It also remembers any intermediate steps between runs.

Additionally, what we've seen is that users want that on a global level. So this works in the scope of a single query execution when you open a query execution window, the history starts there. Now, Lab offers multiple query executions, thus having a global undo/redo is something we are currently working on.
