### ISSUE TITLE
Fix Bolt HELLO message response doesn't contains "server" (default value empty)

### ISSUE THREAD

**Issue by stefanak-michal** [memgraph/memgraph#474]
**Memgraph version**
2.3.1

**Environment**
Windows, Docker, PHP Bolt library

**Describe the bug**
After connecting to memgraph over bolt first message is "hello" to login into. Server response for this message should be map with keys "server" and "connection_id" (optional "hints"). Currently response contains only "connection_id". 

**To Reproduce**
1. Connect to database over bolt and run hello message
2. Analyze response

**Expected behavior**
Response has to contain key "server". Missing key "server" have to contain server agent string identifier like "memgraph/2.3.1".

**Comment by antaljanosbenjamin** [comment]
Hi, I am Benjo from discord! Thanks for reporting this, however this is not a bug in our implementation, more likely a bug in our documentation. If you check our [configuration options for Bolt](https://memgraph.com/docs/memgraph/reference-guide/configuration#bolt), you can see the `--bolt-server-name-for-init` option: "Server name which the database should send to the client in the Bolt INIT message.". Our documentation is unfortunately not clear, because if you don't specify any name, then we won't send the "server" field of the `SUCCESS` message.

However I will leave this issue open until we fix the documentation.

**Comment by stefanak-michal** [comment]
Why you don't have default value?

**Comment by Josipmrden** [comment]
I have put this task into the backlog.

**Comment by alex-linx** [comment]
Hi, +1 on this issue.
I was unable to use python neo4j driver, unless I add `--bolt-server-name-for-init=Neo4j/4.4.0` to the config.
Is there any reason for this not to be the default?
