### ISSUE TITLE
Add indexing properties on relationships, a.k.a. edge indexes

### ISSUE THREAD

**Issue by jhb** [memgraph/memgraph#662]
According to https://memgraph.com/docs/memgraph/reference-guide/indexing it is possible to create indexes on node properties, but no such functionality exists for edges.

IMHO there are a lot of use cases where import properties are put on edges - sometimes the edge properties are even more relevant than the node properties.  E.g. I would like to find all edges that carry a certain date, or are within a range (if modeled with a start and end property). Or edges that carry a certain source of origin, and so on.

While surely the graph could be remodeled with edges as "connection nodes", making this a necessity is not really desirable for graph modeling, and somewhat defeats the purpose of graph databases. Also, competitors have this feature, and migrating data towards memgraph would then require remodeling the whole graph.

IMPORTANT:
* an option is to add node id to each edge -> very memory inefficient at least 16B more for each edge
* another option is to embed vertex IDs inside the index itself -> no memory penalty if the index is not used

PRs:
* https://github.com/memgraph/memgraph/pull/1964

**Comment by gitbuda** [comment]
Hi @jhb!

Definitely a helpful feature :) I/we would consider adding it in the short run, but since we are doing a significant rearchitecting of the Memgraph ([project-pineapples](https://github.com/memgraph/memgraph/tree/project-pineapples) branch), features like this are not a priority at the moment. Once we are done with the groundwork, we'll get back 😄

That being said, one alternative that doesn't require remodeling the whole graph is to store some form of node identifier on the edge (on the application side). If nodes are indexed based on the identifier, once you have an edge, it's possible to query the edge fast because you can access it via node. In other words, having the index on the app side. I know it might not be the perfect solution. Is that feasible in your case?

**Comment by jhb** [comment]
Hi Marko, thanks a lot for your feedback, and of course for your work on memgraph in the first place.

I am looking at different use cases at the moment. For my personal usecase, a generic graph editor (for knowlege management etc.) workarounds in the form of extra nodes that are indexed on behalf of edges might be doable. Those nodes become a bit of a hassle though because they need filtering in the app in all kinds of places - I guess indexing edges outside memgraph would be easier in that case (using a repository layer in front of the graph).

For other use cases (graph analysis etc.) I would imagine the workarounds to become quite cumbersome, because there is not app to carry the extra logic most of the time, and those extra nodes might spoil the experience of interacting directly with the graph.

Having said all this - there is no urgency, and I am looking forward to seeing what changes the pineapples will bring. 

Cheers J

**Comment by Josipmrden** [comment]
Added task to the backlog, although it's not a high priority, we can see what can we do about it at this point.

**Comment by gitbuda** [comment]
+1 request for this feature

**Comment by karmenrabar** [comment]
+1 from the [community](https://discord.com/channels/842007348272169002/842008652377751582/1187484958030299237)

**Comment by Joy-Panda** [comment]
+1 request for this feature

**Comment by ronnie-samaroo** [comment]
+1 request for this feature

**Comment by gitbuda** [comment]
+1 here

**Comment by matea16** [comment]
Hi @jhb, @Joy-Panda and @ronx-labs, I'm happy to inform you that this issue was closed and that Memgraph now supports edge-type indices!
Hopefully this feature will help you elevate your project even more, you can read a more detailed usage description in our [documentation](https://memgraph.com/docs/fundamentals/indexes#edge-type-index)

**Comment by Joy-Panda** [comment]
@matea16 Thank you very much!!!
