### ISSUE TITLE
[BUG] Imported .cypherl is incorre

### ISSUE THREAD

**Issue by csparker247** [memgraph/memgraph#750]
**Memgraph version**
v2.5.1

**Environment**
OS: macOS 13.1
Docker command: `docker run -it -p 7687:7687 -p 7444:7444 -p 3000:3000 memgraph/memgraph-platform`

**Describe the bug**
I'm new to memgraph and was just learning how to create a database. I wrote a simple query to create some basic nodes and connections and saved it to a .cypherl file. When I import this using Memgraph Lab->Import & Export, the nodes are created, but the connections reference unlabeled objects, as evidenced by the generated schema:

<img width="479" alt="Bad schema" src="https://user-images.githubusercontent.com/1434526/214888161-806b7937-daa8-43ca-ba33-7035f947c90d.png">

If I copy-and-paste the same query into the Memgraph Lab query execution editor, it produces the expected result:
 
<img width="419" alt="Good schema" src="https://user-images.githubusercontent.com/1434526/214888754-cc7ae063-2245-4349-be6a-e32afcdb1fff.png">

**To Reproduce**
1. Put the following query into a `.cypherl` file:
```
CREATE (w:Work {name: 'On Rhetoric', author: 'Aristotle'})
CREATE (b:Book {name: 'Book 1'})
CREATE (b)-[:BOOK_OF]->(w)
CREATE (e0:Edition {name: 'A', volumes: 1})
CREATE (e0)-[:EDITION_OF]->(b)
CREATE (e1:Edition {name: 'B', volumes: 2});
```
2. Import the file using the Memgraph Lab->Import & Export UI.

**Expected behavior**
The database should consist of properly connected nodes and a schema identical to the good schema posted above. 

**Logs**
The logs in Memgraph Lab are effectively empty:
```
[2023-01-26 16:19:10.912] ~ Successfully connected to Memgraph logs. If there are no new logs please check your --log-level settings.
```

**Comment by katarinasupe** [comment]
Hi @csparker247, thank you for the report. This is an expected behavior with Memgraph Lab and `cypherl` files.
So, the issue here is that you created a `cypherl` file and expected it to work the same as you execute queries from the Memgraph Lab. The difference is that the queries in the `cypherl` file are being executed line by line - each line represents one transaction. Hence, when, for example, `query CREATE (b)-[:BOOK_OF]->(w)` is being executed, it creates a node without a label connected to another node without a label with the relationship of type `BOOK_OF`.

So, to avoid that, when creating a `cypherl` file, you need to be careful to first match already created nodes or relationships like this:
```
CREATE (w:Work {name: 'On Rhetoric', author: 'Aristotle'});
CREATE (b:Book {name: 'Book 1'});
MATCH (b:Book {name: 'Book 1'}), (w:Work {name: 'On Rhetoric', author: 'Aristotle'}) CREATE (b)-[:BOOK_OF]->(w);
MATCH (b:Book {name: 'Book 1'}) CREATE (e0:Edition {name: 'A', volumes: 1})-[:EDITION_OF]->(b)
CREATE (e1:Edition {name: 'B', volumes: 2});
```

If you import such a file, I think the dataset will be fine.

On the other hand, if you want to get the `cypherl` file out of your existing dataset, you can export it by navigating to the Import & Export tab. That `cypherl` file looks slightly different than what I provided above, but it works almost the same.

```
CREATE INDEX ON :__mg_vertex__(__mg_id__);
CREATE (:__mg_vertex__:`Work` {__mg_id__: 0, `name`: "On Rhetoric", `author`: "Aristotle"});
CREATE (:__mg_vertex__:`Book` {__mg_id__: 1, `name`: "Book 1"});
CREATE (:__mg_vertex__:`Edition` {__mg_id__: 2, `name`: "A", `volumes`: 1});
CREATE (:__mg_vertex__:`Edition` {__mg_id__: 3, `name`: "B", `volumes`: 2});
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 1 AND v.__mg_id__ = 0 CREATE (u)-[:`BOOK_OF`]->(v);
MATCH (u:__mg_vertex__), (v:__mg_vertex__) WHERE u.__mg_id__ = 2 AND v.__mg_id__ = 1 CREATE (u)-[:`EDITION_OF`]->(v);
DROP INDEX ON :__mg_vertex__(__mg_id__);
MATCH (u) REMOVE u:__mg_vertex__, u.__mg_id__;
```

It creates indexes before import for faster import and drops them in the end. Also, it first creates all nodes and then does the necessary matching with generated ids.

**Comment by csparker247** [comment]
> So, the issue here is that you created a `cypherl` file and expected it to work the same as you execute queries from the Memgraph Lab. The difference is that the queries in the `cypherl` file are being executed line by line - each line represents one transaction.

Ah ha! The missing piece! I was starting to wonder if that was the case, but didn't see it documented anywhere. Thank you very much! I can easily make those adjustments.
