### ISSUE TITLE
Add support for TTL - Time to Live

### ISSUE THREAD

**Issue by antejavor** [memgraph/memgraph#856]
The time to live feature automatically deletes nodes that have set expiration times or dates specified. 

### Discord Conversations
* https://discord.com/channels/842007348272169002/890969266600423504/1091118610874904606
* https://discord.com/channels/842007348272169002/890968055339958292/1227881931144826890

### Additional Requirements

* Instead of deleting graph elements, store them on colder storage (on-disk). Implement the ability to query the colder storage for the deleted data.

**Comment by insectatorious** [comment]
Agree that this is pretty crucial feature for any production deployment. In addition to the exellent ones already mentioned on the discord thread, I can add:

- Customer interactions (basket adds, removals etc) for an e-commerce platform. Vital for recommendation models (until they have been aggregated by an appropriate data pipeline). Eg, TTL for interactions that result in an order being placed is different from that where no order is placed and the basket is abandoned. 
- Storing recommendations for different purposes - moving stock (eg Clearance) vs increasing revenue per unit. These can be refreshed as model inference runs but you would expect the recommendations to go 'stale' after a certain amount of time and it is better to return nothing than returning outdated product recommendations.

**Comment by tgperkins** [comment]
Neo4j as a comparison, already has TTL support for nodes. TTL support on edges would also be highly desirable.
https://neo4j.com/labs/apoc/5/graph-updates/ttl/
https://neo4j.com/labs/apoc/5/config/

**Comment by Josipmrden** [comment]
Hello @insectatorious  and @tgperkins . Currently TTL features are not in our roadmap. I might suggest a workaround that you do set a property of a node or an edge to be the expiry date and then periodically do the cleanup via an external script which does the querying (i.e. searching for expired nodes and deleting connections)

**Comment by ekcoote** [comment]
I would also like to see TTL features supported. It would help keep large graphs manageable and relevant for research purposes

**Comment by gitbuda** [comment]
Hi all! This is definitely an interesting feature. I wouldn't say it's critical for any production deployment because many production deployments do not require it. Still, I 100% understand this can have a critical role in many real-world system and production deployments.

I was thinking about how to implement the feature. There are many challenges that ofc could be solved. In the transactional environment, there is a problem of conflicting writes (when some expired node/edge has to be deleted while there is some write transaction trying to update the same node); there is also a huge topic how do you TTL on a replicated cluster 🤔 

But, in the [analytical environment](https://memgraph.com/docs/memgraph/reference-guide/storage-modes#analytical-storage-mode), the whole thing seems much easier to achieve + without any extra memory overhead (in the Memgraph case, because of how Memgraph storage is implemented).

So, my question for @ekcoote, @insectatorious, @tgperkins is: **Is is feasible for you to run Memgraph in the analytics mode?** If not, a brief explanation of why would help 😄 The reason I'm asking is that if we have more people which are ok with the combination, I think we can make a quick PoC 👀

**Comment by tgperkins** [comment]
@gitbuda While I see some use cases that would benefit from transactional TTL support, it would be more of a nice to have not a requirement. I would assume that most use cases would be in analytical mode that would require TTLs. 

The main concern for those of us in the situation where you have infinite unique nodes and edges is that you will run out of memory at some point. Suppose analytical mode is acceptable for your use case. In that case, all that would be needed is an internal function that would trigger a graph cleanup every t seconds or when a memory limit is hit, deleting data where a TTL field has been exceeded. Maybe implementing it like a constraint similar to:
CREATE CONSTRAINT ON (n:label) ASSERT TTL (n.property, integer, time unit);

**Comment by katarinasupe** [comment]
+1 from the community with the additional comment that in-memory analytical storage mode wouldn't be feasible. [Source](https://discord.com/channels/842007348272169002/890968055339958292/1227881931144826890).

**Comment by gitbuda** [comment]
Quick update here 😄 As you (@insectatorious, @tgperkins, @ekcoote) might have noticed, the initial implementation of TTL has been merged to master, and the feature will be released as a part of [v2.19](https://github.com/memgraph/memgraph/milestone/22) mid this week. The documentation is part of the [following PR](https://github.com/memgraph/documentation/pull/913). Any feedback is very welcome!

**Comment by katarinasupe** [comment]
Just a heads up here - TTL is an Enterprise feature. If you'd like to try it out, you can [request Enterprise trial](https://memgraph.com/enterprise-trial). If you need any help or would like to talk more about TTL and your use case, please [schedule and office hours call ](https://memgraph.com/office-hours)with the developer experience team 😄
