### ISSUE TITLE
Implement return of transaction id on RUN / BEGIN

### ISSUE THREAD

**Issue by gitbuda** [memgraph/memgraph#934]
* With this, client apps, most notably Memgraph Lab, could easily terminate initiated transactions.
* Probably the base way is to add transaction id into the `fields` inside the `SUCCESS` message -> https://neo4j.com/docs/bolt/current/bolt/message/#messages-success
* The transaction info should be returned for both single and multi-query transactions

**Comment by andrejtonev** [comment]
The Bolt protocol doesn't have a transaction id. One session can have a single transaction at a time (https://neo4j.com/docs/python-manual/current/transactions/).
Would the transaction id be a Memgraph specific addition?
Do we even need it, since the client can just keep track of the session and terminate that way?

In addition, we should review the Reset implementation to make sure it is compliant (this gets into the bigger picture of the state machine mirroring).

**Comment by andrejtonev** [comment]
https://github.com/memgraph/memgraph/pull/945

**Comment by gitbuda** [comment]
Figure out do we have to do something else here...
