### ISSUE TITLE
Fix GC is not kicking off on configured time

### ISSUE THREAD

**Issue by jyenduri-uptycs** [memgraph/memgraph#980]
**Memgraph version**
2.8.0

**Environment**
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1031-aws x86_64)
memgraphdb running as docker

**Describe the bug**
 GC is not kicking off on configured time . We have set it -storage-gc-cycle-sec to 15 seconds and we dont see memory not freeing up on configured time.

**Comment by antejavor** [comment]
This also relates to the FREE MEMORY, which is also present in IN-MEMORY-TRANSACTIONAL. 
And here is a bit of context: 
So on: ` MATCH (n) DETACH DELETE n; ` and `FREE MEMORY `

The memory does not get deleted for some time because of the following reasons: 
Basically from FreeMemory or GC cycle there is a long wait until things are actually deallocated.
Deltas and vertices can be unlinked from the current structures but can not be deleted until no accessors/transactions are looking at them.
Then even if deleted, jemalloc will hold onto them for a bit before giving back to the OS. This is more efficient for high memory acquire/release. Even with that, ATM our memory allocation is the best. It can become quite fragmented because many of those allocation arenas are common to the system (rather than focused on the query).


This behavior is somewhat expected at the moment, but will be improved.

**Comment by gitbuda** [comment]
Maybe related to #745

**Comment by as51340** [comment]
GC kicks off as expected, the actual problem is that the memory isn't cleared immediately when GC is called. This is similar to #1220 .
